import React from 'react';
import { FaBackspace } from 'react-icons/fa';
import { Theme, ButtonConfig, ButtonType } from './types';

export const DEFAULT_THEME = 'Cyberpunk';

export const THEMES: { [key: string]: Theme } = {
  'Cyberpunk': {
    name: 'Cyberpunk',
    colors: {
      '--background': '#0d0221',
      '--calculator-body': 'rgba(26, 9, 58, 0.6)',
      '--calculator-shadow': 'rgba(119, 34, 255, 0.4)',
      '--display-bg': 'rgba(13, 2, 33, 0.8)',
      '--display-text': '#00f7ff',
      '--text-primary': '#f0f0f0',
      '--text-secondary': '#a0a0c0',
      '--btn-number-bg': 'rgba(42, 21, 88, 0.7)',
      '--btn-number-text': '#e0e0ff',
      '--btn-number-border': '#3a1f7a',
      '--btn-operator-bg': 'rgba(68, 30, 138, 0.8)',
      '--btn-operator-text': '#00f7ff',
      '--btn-operator-border': '#5a28c8',
      '--btn-function-bg': 'rgba(119, 34, 255, 0.3)',
      '--btn-function-text': '#ff40c4',
      '--btn-function-border': '#7722ff',
      '--btn-equal-bg': '#00f7ff',
      '--btn-equal-text': '#0d0221',
      '--btn-equal-border': '#00f7ff',
    },
  },
  'Synthwave': {
    name: 'Synthwave',
    colors: {
       '--background': '#201335',
       '--calculator-body': 'rgba(32, 19, 53, 0.7)',
       '--calculator-shadow': 'rgba(255, 59, 148, 0.3)',
       '--display-bg': 'rgba(44, 27, 75, 0.9)',
       '--display-text': '#ff6ac1',
       '--text-primary': '#ffffff',
       '--text-secondary': '#b3aed4',
       '--btn-number-bg': 'rgba(69, 44, 116, 0.6)',
       '--btn-number-text': '#ffffff',
       '--btn-number-border': '#55348f',
       '--btn-operator-bg': 'rgba(138, 71, 255, 0.5)',
       '--btn-operator-text': '#f9f871',
       '--btn-operator-border': '#8a47ff',
       '--btn-function-bg': 'rgba(255, 59, 148, 0.3)',
       '--btn-function-text': '#ff6ac1',
       '--btn-function-border': '#ff3b94',
       '--btn-equal-bg': '#f9f871',
       '--btn-equal-text': '#201335',
       '--btn-equal-border': '#f9f871',
    },
  },
  'Classic Light': {
    name: 'Classic Light',
    colors: {
      '--background': '#f0f2f5',
      '--calculator-body': '#ffffff',
      '--calculator-shadow': 'rgba(0, 0, 0, 0.1)',
      '--display-bg': '#f9f9f9',
      '--display-text': '#333333',
      '--text-primary': '#222222',
      '--text-secondary': '#666666',
      '--btn-number-bg': '#f7f7f7',
      '--btn-number-text': '#333333',
      '--btn-number-border': '#e0e0e0',
      '--btn-operator-bg': '#f0f0f0',
      '--btn-operator-text': '#ff6f00',
      '--btn-operator-border': '#d9d9d9',
      '--btn-function-bg': '#e9e9e9',
      '--btn-function-text': '#4a4a4a',
      '--btn-function-border': '#cccccc',
      '--btn-equal-bg': '#ff6f00',
      '--btn-equal-text': '#ffffff',
      '--btn-equal-border': '#ff6f00',
    },
  },
};

export const basicButtons: ButtonConfig[] = [
    { label: 'C', value: 'clear', type: ButtonType.Function },
    // FIX: The button configuration for backspace was missing the `value` and `type` properties, causing it to not conform to the `ButtonConfig` type.
    { label: <FaBackspace />, value: 'backspace', type: ButtonType.Function },
    { label: '%', value: '%', type: ButtonType.Operator },
    { label: '÷', value: '/', type: ButtonType.Operator },
    { label: '7', value: '7', type: ButtonType.Number },
    { label: '8', value: '8', type: ButtonType.Number },
    { label: '9', value: '9', type: ButtonType.Number },
    { label: '×', value: '*', type: ButtonType.Operator },
    { label: '4', value: '4', type: ButtonType.Number },
    { label: '5', value: '5', type: ButtonType.Number },
    { label: '6', value: '6', type: ButtonType.Number },
    { label: '-', value: '-', type: ButtonType.Operator },
    { label: '1', value: '1', type: ButtonType.Number },
    { label: '2', value: '2', type: ButtonType.Number },
    { label: '3', value: '3', type: ButtonType.Number },
    { label: '+', value: '+', type: ButtonType.Operator },
    { label: '0', value: '0', type: ButtonType.Number, gridSpan: 2 },
    { label: '.', value: '.', type: ButtonType.Number },
    { label: '=', value: 'equals', type: ButtonType.Equal },
];

export const scientificButtons: ButtonConfig[] = [
    { label: 'sin', value: 'sin(', type: ButtonType.Function },
    { label: 'cos', value: 'cos(', type: ButtonType.Function },
    { label: 'tan', value: 'tan(', type: ButtonType.Function },
    { label: 'log₁₀', value: 'log10(', type: ButtonType.Function },
    { label: 'ln', value: 'log(', type: ButtonType.Function },
    { label: '√', value: 'sqrt(', type: ButtonType.Function },
    { label: 'x²', value: '^2', type: ButtonType.Function },
    { label: 'π', value: 'π', type: ButtonType.Function },
    { label: 'e', value: 'e', type: ButtonType.Function },
    { label: '(', value: '(', type: ButtonType.Function },
    { label: ')', value: ')', type: ButtonType.Function },
];